/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IFareToken,
  IFareTokenInterface,
} from "../../../contracts/interfaces/IFareToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "player",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "burnFare",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "player",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "mintFare",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IFareToken__factory {
  static readonly abi = _abi;
  static createInterface(): IFareTokenInterface {
    return new utils.Interface(_abi) as IFareTokenInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFareToken {
    return new Contract(address, _abi, signerOrProvider) as IFareToken;
  }
}
