/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IFareItems,
  IFareItemsInterface,
} from "../../../contracts/interfaces/IFareItems";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "exists",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256[]",
        name: "ids",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "amounts",
        type: "uint256[]",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "mintBatch",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IFareItems__factory {
  static readonly abi = _abi;
  static createInterface(): IFareItemsInterface {
    return new utils.Interface(_abi) as IFareItemsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFareItems {
    return new Contract(address, _abi, signerOrProvider) as IFareItems;
  }
}
