/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { FareItems } from "./FareItems";
export type { FareNFTLootBox } from "./FareNFTLootBox";
export type { FareNFTLootBoxController } from "./FareNFTLootBoxController";
export type { FareSpinGame } from "./FareSpinGame";
export type { FareToken } from "./FareToken";
