branch-defaults:
  feature/gitlab-ci:
    environment: fp-api-test
environment-defaults:
  fp-api-test:
    branch: null
    repository: null
global:
  application_name: fp-api
  default_ec2_keyname: gitlab-ci-west
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
