image: node:lts

stages:
  - setup
  - lint
  - build

variables:
  CI: "true"

cache: &global_cache
  key: $CI_COMMIT_REF_SLUG
  paths:
    - server/node_modules/
  policy: pull-push

setup:
  stage: setup
  script:
    - echo 'INSTALLING DEPENDENCIES'
    - cd server/
    - rm -rf node_modules/
    - npm install --include=dev
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - server/node_modules/

lint:
  stage: lint
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - server/node_modules/
    policy: pull
  script:
    - echo 'LINT'
    - cd server/
    - npm run lint-ci

build:
  stage: build
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - server/node_modules/
    policy: pull
  script:
    - echo 'BUILD'
    - cd server/
    - npm run build
