image: node:lts

stages:
  - setup
  - lint
  - build
  - deploy-test

# These variables will default to those appropriate to deploy
#   the test environment. Manual build steps will deploy to
#   other environments for now.
variables:
  CI: "true"
  AWS_REGION: us-west-2
  APP_NAME: fp-api
  ENV_NAME: fp-api-test
  FILE: $CI_COMMIT_REF_NAME-$CI_PIPELINE_ID
  BUILD_DIR: $CI_PROJECT_DIR/builds
  BUILD_FILENAME: $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID.zip
  BUILD_FILE: $BUILD_DIR/$BUILD_FILENAME
  BUCKET: elasticbeanstalk-us-west-2-390985807324
  BUCKET_PREFIX: builds/test
  AWS_PLATFORM: Docker
  KEY: gitlab-ci-west

cache: &global_cache
  key: $CI_COMMIT_REF_SLUG
  paths:
    - server/node_modules/
  policy: pull-push

setup:
  stage: setup
  script:
    - echo 'INSTALLING DEPENDENCIES'
    - cd server/
    - rm -rf node_modules/
    - npm install --include=dev
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - server/node_modules/

lint:
  stage: lint
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - server/node_modules/
    policy: pull
  script:
    - echo 'LINT'
    - cd server/
    - npm run lint-ci

build:
  stage: build
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - server/node_modules/
    policy: pull
  script:
    - echo 'BUILD'
    - apt-get update -y && apt-get install -y zip
    - cd server/
    - npm run build
    - mkdir -p $BUILD_DIR
    - zip -r $BUILD_FILE ./dist/*
    - ls $BUILD_DIR
  artifacts:
    paths:
      - $BUILD_FILE

deploy-test:
  image: python:latest
  stage: deploy-test
  script:
    - pip install awscli
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region $AWS_REGION
    - aws s3 cp $BUILD_FILE s3://$BUCKET/$BUCKET_PREFIX/$BUILD_FILENAME
    - |
      aws elasticbeanstalk create-application-version \
        --application-name $APP_NAME \
        --version-label v_$CI_COMMIT_SHORT_SHA \
        --source-bundle S3Bucket=$BUCKET,S3Key=$BUCKET_PREFIX/$BUILD_FILENAME
    - aws elasticbeanstalk update-environment --environment-name $ENV_NAME --version-label v_$CI_COMMIT_SHORT_SHA
  dependencies:
    - build
