stages:
  - lint
  - test
  - deploy

cache: &global_cache
  key: $CI_COMMIT_REF_SLUG
  paths:
    - server/node_modules/
  policy: pull-push

lint:
  stage: lint
  script:
    - cd server/
    - npm install --include=dev
    - npm run lint
