version: '3.9'
services:
  fareplay-store:
    image: mongo:latest
    restart: always
    container_name: fareplay-store
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE_NAME}
    ports:
      - 27017:27017
    volumes:
      - fare-store-data:${MONGO_STORE_DBPATH}
      - ./bin/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
  fareplay-redis:
    image: redis/redis-stack-server:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - fare-cache:/data
  fareplay-server:
    image: fp-backend:latest
    network_mode: host
    profiles: ['server']
networks:
  default:
    name: fareplay-bridge-network
    driver: bridge
volumes:
  fare-store-data:
    driver: local
  fare-cache:
    driver: local
