enum MESSAGES {
	NEW_CHAT_MESSAGE = 'NEW_CHAT_MESSAGE',
	NEW_SCREEN_SHARE = 'NEW_SCREEN_SHARE',
	TOGGLE_SCREEN_SHARE = 'TOGGLE_SCREEN_SHARE',
	STOP_SCREEN_SHARE = 'STOP_SCREEN_SHARE',
}

export default MESSAGES
