/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export declare namespace FareSpin {
  export type EliminatorStruct = {
    contractModeId: BigNumberish;
    recordedExpectedValueFloor: BigNumberish;
    isEliminator: boolean;
  };

  export type EliminatorStructOutput = [BigNumber, BigNumber, boolean] & {
    contractModeId: BigNumber;
    recordedExpectedValueFloor: BigNumber;
    isEliminator: boolean;
  };

  export type EntryStruct = {
    amount: BigNumberish;
    contractModeId: BigNumberish;
    pickedNumber: BigNumberish;
  };

  export type EntryStructOutput = [BigNumber, BigNumber, BigNumber] & {
    amount: BigNumber;
    contractModeId: BigNumber;
    pickedNumber: BigNumber;
  };
}

export interface FareSpinInterface extends utils.Interface {
  contractName: "FareSpin";

  functions: {
    "CONTRACT_EXPECTED_VALUE_CEILING()": FunctionFragment;
    "TREASURY_MINT_CAP()": FunctionFragment;
    "batchEntryMap(uint256,address)": FunctionFragment;
    "contractModes(uint256)": FunctionFragment;
    "getAllUsersByRoundId(uint256)": FunctionFragment;
    "getBatchEntryCount(uint256)": FunctionFragment;
    "getCurrentContractModeId()": FunctionFragment;
    "getCurrentRoundId()": FunctionFragment;
    "getEliminatorsByRoundId(uint256)": FunctionFragment;
    "getEntriesByRoundUser(uint256,address)": FunctionFragment;
    "getEntryByIndex(uint256,address,uint256)": FunctionFragment;
    "getEntryCount(uint256,address)": FunctionFragment;
    "getFareTokenAddress()": FunctionFragment;
    "getIsEliminator(uint256,uint256)": FunctionFragment;
    "isRoundPaused()": FunctionFragment;
    "owner()": FunctionFragment;
    "paused()": FunctionFragment;
    "placeBatchEntry((uint256,uint256,uint256)[])": FunctionFragment;
    "rawFulfillRandomness(bytes32,uint256)": FunctionFragment;
    "requestRandomNumber()": FunctionFragment;
    "rounds(uint256)": FunctionFragment;
    "setContractExpectedValueFloor(uint256,uint256)": FunctionFragment;
    "setContractMode(uint256,uint256,uint256,uint256,uint256,uint256)": FunctionFragment;
    "setContractModeEntryLimit(uint256,uint256)": FunctionFragment;
    "setContractModeIsActive(uint256,bool)": FunctionFragment;
    "setContractModeMinMax(uint256,uint256,uint256)": FunctionFragment;
    "setFareToken(address)": FunctionFragment;
    "setPauseContract(bool)": FunctionFragment;
    "setRoundPaused(bool)": FunctionFragment;
    "setTreasuryAddress(address)": FunctionFragment;
    "setTreasuryMint(uint256)": FunctionFragment;
    "settleBatchEntry(uint256,address)": FunctionFragment;
    "testConcludeRound(bytes32)": FunctionFragment;
    "testFulfillRandomness(bytes32,uint256)": FunctionFragment;
    "treasuryAddress()": FunctionFragment;
    "treasuryMint()": FunctionFragment;
    "vrfCoordinator()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "CONTRACT_EXPECTED_VALUE_CEILING"
      | "TREASURY_MINT_CAP"
      | "batchEntryMap"
      | "contractModes"
      | "getAllUsersByRoundId"
      | "getBatchEntryCount"
      | "getCurrentContractModeId"
      | "getCurrentRoundId"
      | "getEliminatorsByRoundId"
      | "getEntriesByRoundUser"
      | "getEntryByIndex"
      | "getEntryCount"
      | "getFareTokenAddress"
      | "getIsEliminator"
      | "isRoundPaused"
      | "owner"
      | "paused"
      | "placeBatchEntry"
      | "rawFulfillRandomness"
      | "requestRandomNumber"
      | "rounds"
      | "setContractExpectedValueFloor"
      | "setContractMode"
      | "setContractModeEntryLimit"
      | "setContractModeIsActive"
      | "setContractModeMinMax"
      | "setFareToken"
      | "setPauseContract"
      | "setRoundPaused"
      | "setTreasuryAddress"
      | "setTreasuryMint"
      | "settleBatchEntry"
      | "testConcludeRound"
      | "testFulfillRandomness"
      | "treasuryAddress"
      | "treasuryMint"
      | "vrfCoordinator"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "CONTRACT_EXPECTED_VALUE_CEILING",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TREASURY_MINT_CAP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "batchEntryMap",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "contractModes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllUsersByRoundId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBatchEntryCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentContractModeId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentRoundId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEliminatorsByRoundId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntriesByRoundUser",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntryByIndex",
    values: [BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntryCount",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getFareTokenAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getIsEliminator",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isRoundPaused",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "placeBatchEntry",
    values: [FareSpin.EntryStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "rawFulfillRandomness",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestRandomNumber",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rounds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setContractExpectedValueFloor",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setContractMode",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setContractModeEntryLimit",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setContractModeIsActive",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setContractModeMinMax",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFareToken",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setPauseContract",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setRoundPaused",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasuryAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasuryMint",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "settleBatchEntry",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "testConcludeRound",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "testFulfillRandomness",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "treasuryAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "treasuryMint",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "vrfCoordinator",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "CONTRACT_EXPECTED_VALUE_CEILING",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TREASURY_MINT_CAP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchEntryMap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contractModes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllUsersByRoundId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBatchEntryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentContractModeId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentRoundId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEliminatorsByRoundId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEntriesByRoundUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEntryByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEntryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFareTokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIsEliminator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRoundPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "placeBatchEntry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rawFulfillRandomness",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestRandomNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rounds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setContractExpectedValueFloor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setContractMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setContractModeEntryLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setContractModeIsActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setContractModeMinMax",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFareToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPauseContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRoundPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasuryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasuryMint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleBatchEntry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testConcludeRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testFulfillRandomness",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "treasuryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "treasuryMint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vrfCoordinator",
    data: BytesLike
  ): Result;

  events: {
    "ContractModeUpdated(uint256)": EventFragment;
    "EntrySettled(uint256,address,bool)": EventFragment;
    "EntrySubmitted(uint256,uint256,address)": EventFragment;
    "NFTMint(uint256,address)": EventFragment;
    "Paused(address)": EventFragment;
    "RandomNumberRequested(bytes32)": EventFragment;
    "RoundConcluded(uint256,bytes32,uint256,uint256)": EventFragment;
    "RoundPausedChanged(bool)": EventFragment;
    "Unpaused(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ContractModeUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EntrySettled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EntrySubmitted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NFTMint"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RandomNumberRequested"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoundConcluded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoundPausedChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
}

export interface ContractModeUpdatedEventObject {
  contractModeId: BigNumber;
}
export type ContractModeUpdatedEvent = TypedEvent<
  [BigNumber],
  ContractModeUpdatedEventObject
>;

export type ContractModeUpdatedEventFilter =
  TypedEventFilter<ContractModeUpdatedEvent>;

export interface EntrySettledEventObject {
  roundId: BigNumber;
  user: string;
  hasMinted: boolean;
}
export type EntrySettledEvent = TypedEvent<
  [BigNumber, string, boolean],
  EntrySettledEventObject
>;

export type EntrySettledEventFilter = TypedEventFilter<EntrySettledEvent>;

export interface EntrySubmittedEventObject {
  roundId: BigNumber;
  batchId: BigNumber;
  user: string;
}
export type EntrySubmittedEvent = TypedEvent<
  [BigNumber, BigNumber, string],
  EntrySubmittedEventObject
>;

export type EntrySubmittedEventFilter = TypedEventFilter<EntrySubmittedEvent>;

export interface NFTMintEventObject {
  roundId: BigNumber;
  user: string;
}
export type NFTMintEvent = TypedEvent<[BigNumber, string], NFTMintEventObject>;

export type NFTMintEventFilter = TypedEventFilter<NFTMintEvent>;

export interface PausedEventObject {
  account: string;
}
export type PausedEvent = TypedEvent<[string], PausedEventObject>;

export type PausedEventFilter = TypedEventFilter<PausedEvent>;

export interface RandomNumberRequestedEventObject {
  vrfRequestId: string;
}
export type RandomNumberRequestedEvent = TypedEvent<
  [string],
  RandomNumberRequestedEventObject
>;

export type RandomNumberRequestedEventFilter =
  TypedEventFilter<RandomNumberRequestedEvent>;

export interface RoundConcludedEventObject {
  roundId: BigNumber;
  vrfRequestId: string;
  randomNum: BigNumber;
  randomEliminator: BigNumber;
}
export type RoundConcludedEvent = TypedEvent<
  [BigNumber, string, BigNumber, BigNumber],
  RoundConcludedEventObject
>;

export type RoundConcludedEventFilter = TypedEventFilter<RoundConcludedEvent>;

export interface RoundPausedChangedEventObject {
  isPaused: boolean;
}
export type RoundPausedChangedEvent = TypedEvent<
  [boolean],
  RoundPausedChangedEventObject
>;

export type RoundPausedChangedEventFilter =
  TypedEventFilter<RoundPausedChangedEvent>;

export interface UnpausedEventObject {
  account: string;
}
export type UnpausedEvent = TypedEvent<[string], UnpausedEventObject>;

export type UnpausedEventFilter = TypedEventFilter<UnpausedEvent>;

export interface FareSpin extends BaseContract {
  contractName: "FareSpin";

  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: FareSpinInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    CONTRACT_EXPECTED_VALUE_CEILING(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    TREASURY_MINT_CAP(overrides?: CallOverrides): Promise<[BigNumber]>;

    batchEntryMap(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, boolean, BigNumber, BigNumber] & {
        batchEntryId: BigNumber;
        user: string;
        settled: boolean;
        totalEntryAmount: BigNumber;
        totalMintAmount: BigNumber;
      }
    >;

    contractModes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        boolean
      ] & {
        id: BigNumber;
        cardinality: BigNumber;
        contractExpectedValueFloor: BigNumber;
        mintMultiplier: BigNumber;
        minAmount: BigNumber;
        maxAmount: BigNumber;
        entryLimit: BigNumber;
        isActive: boolean;
      }
    >;

    getAllUsersByRoundId(
      roundId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string[]] & { users: string[] }>;

    getBatchEntryCount(
      roundId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { count: BigNumber }>;

    getCurrentContractModeId(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { id: BigNumber }>;

    getCurrentRoundId(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { id: BigNumber }>;

    getEliminatorsByRoundId(
      roundId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [FareSpin.EliminatorStructOutput[]] & {
        eliminators: FareSpin.EliminatorStructOutput[];
      }
    >;

    getEntriesByRoundUser(
      roundId: BigNumberish,
      user: string,
      overrides?: CallOverrides
    ): Promise<[FareSpin.EntryStructOutput[]]>;

    getEntryByIndex(
      roundId: BigNumberish,
      user: string,
      entryIdx: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[FareSpin.EntryStructOutput]>;

    getEntryCount(
      roundId: BigNumberish,
      user: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { count: BigNumber }>;

    getFareTokenAddress(
      overrides?: CallOverrides
    ): Promise<[string] & { fareAddress: string }>;

    getIsEliminator(
      roundId: BigNumberish,
      contractModeId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean] & { isEliminator: boolean }>;

    isRoundPaused(overrides?: CallOverrides): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    placeBatchEntry(
      entries: FareSpin.EntryStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    rawFulfillRandomness(
      requestId: BytesLike,
      randomness: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    requestRandomNumber(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    rounds(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, string, BigNumber] & {
        id: BigNumber;
        randomNum: BigNumber;
        randomEliminator: BigNumber;
        vrfRequestId: string;
        vrfNum: BigNumber;
      }
    >;

    setContractExpectedValueFloor(
      contractModeId: BigNumberish,
      _contractExpectedValueFloor: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setContractMode(
      cardinality: BigNumberish,
      contractExpectedValueFloor: BigNumberish,
      mintMultiplier: BigNumberish,
      minAmount: BigNumberish,
      maxAmount: BigNumberish,
      entryLimit: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setContractModeEntryLimit(
      contractModeId: BigNumberish,
      entryLimit: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setContractModeIsActive(
      contractModeId: BigNumberish,
      isActive: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setContractModeMinMax(
      contractModeId: BigNumberish,
      minAmount: BigNumberish,
      maxAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setFareToken(
      _fareTokenAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setPauseContract(
      paused: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setRoundPaused(
      paused: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setTreasuryAddress(
      _treasuryAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setTreasuryMint(
      percent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    settleBatchEntry(
      roundId: BigNumberish,
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testConcludeRound(
      vrfRequestId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testFulfillRandomness(
      vrfRequestId: BytesLike,
      randomness: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    treasuryAddress(overrides?: CallOverrides): Promise<[string]>;

    treasuryMint(overrides?: CallOverrides): Promise<[BigNumber]>;

    vrfCoordinator(overrides?: CallOverrides): Promise<[string]>;
  };

  CONTRACT_EXPECTED_VALUE_CEILING(
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  TREASURY_MINT_CAP(overrides?: CallOverrides): Promise<BigNumber>;

  batchEntryMap(
    arg0: BigNumberish,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, boolean, BigNumber, BigNumber] & {
      batchEntryId: BigNumber;
      user: string;
      settled: boolean;
      totalEntryAmount: BigNumber;
      totalMintAmount: BigNumber;
    }
  >;

  contractModes(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      boolean
    ] & {
      id: BigNumber;
      cardinality: BigNumber;
      contractExpectedValueFloor: BigNumber;
      mintMultiplier: BigNumber;
      minAmount: BigNumber;
      maxAmount: BigNumber;
      entryLimit: BigNumber;
      isActive: boolean;
    }
  >;

  getAllUsersByRoundId(
    roundId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getBatchEntryCount(
    roundId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getCurrentContractModeId(overrides?: CallOverrides): Promise<BigNumber>;

  getCurrentRoundId(overrides?: CallOverrides): Promise<BigNumber>;

  getEliminatorsByRoundId(
    roundId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<FareSpin.EliminatorStructOutput[]>;

  getEntriesByRoundUser(
    roundId: BigNumberish,
    user: string,
    overrides?: CallOverrides
  ): Promise<FareSpin.EntryStructOutput[]>;

  getEntryByIndex(
    roundId: BigNumberish,
    user: string,
    entryIdx: BigNumberish,
    overrides?: CallOverrides
  ): Promise<FareSpin.EntryStructOutput>;

  getEntryCount(
    roundId: BigNumberish,
    user: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getFareTokenAddress(overrides?: CallOverrides): Promise<string>;

  getIsEliminator(
    roundId: BigNumberish,
    contractModeId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isRoundPaused(overrides?: CallOverrides): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  placeBatchEntry(
    entries: FareSpin.EntryStruct[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  rawFulfillRandomness(
    requestId: BytesLike,
    randomness: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  requestRandomNumber(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  rounds(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, string, BigNumber] & {
      id: BigNumber;
      randomNum: BigNumber;
      randomEliminator: BigNumber;
      vrfRequestId: string;
      vrfNum: BigNumber;
    }
  >;

  setContractExpectedValueFloor(
    contractModeId: BigNumberish,
    _contractExpectedValueFloor: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setContractMode(
    cardinality: BigNumberish,
    contractExpectedValueFloor: BigNumberish,
    mintMultiplier: BigNumberish,
    minAmount: BigNumberish,
    maxAmount: BigNumberish,
    entryLimit: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setContractModeEntryLimit(
    contractModeId: BigNumberish,
    entryLimit: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setContractModeIsActive(
    contractModeId: BigNumberish,
    isActive: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setContractModeMinMax(
    contractModeId: BigNumberish,
    minAmount: BigNumberish,
    maxAmount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setFareToken(
    _fareTokenAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setPauseContract(
    paused: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setRoundPaused(
    paused: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setTreasuryAddress(
    _treasuryAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setTreasuryMint(
    percent: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  settleBatchEntry(
    roundId: BigNumberish,
    user: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testConcludeRound(
    vrfRequestId: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testFulfillRandomness(
    vrfRequestId: BytesLike,
    randomness: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  treasuryAddress(overrides?: CallOverrides): Promise<string>;

  treasuryMint(overrides?: CallOverrides): Promise<BigNumber>;

  vrfCoordinator(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    CONTRACT_EXPECTED_VALUE_CEILING(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    TREASURY_MINT_CAP(overrides?: CallOverrides): Promise<BigNumber>;

    batchEntryMap(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, boolean, BigNumber, BigNumber] & {
        batchEntryId: BigNumber;
        user: string;
        settled: boolean;
        totalEntryAmount: BigNumber;
        totalMintAmount: BigNumber;
      }
    >;

    contractModes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        boolean
      ] & {
        id: BigNumber;
        cardinality: BigNumber;
        contractExpectedValueFloor: BigNumber;
        mintMultiplier: BigNumber;
        minAmount: BigNumber;
        maxAmount: BigNumber;
        entryLimit: BigNumber;
        isActive: boolean;
      }
    >;

    getAllUsersByRoundId(
      roundId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getBatchEntryCount(
      roundId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCurrentContractModeId(overrides?: CallOverrides): Promise<BigNumber>;

    getCurrentRoundId(overrides?: CallOverrides): Promise<BigNumber>;

    getEliminatorsByRoundId(
      roundId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<FareSpin.EliminatorStructOutput[]>;

    getEntriesByRoundUser(
      roundId: BigNumberish,
      user: string,
      overrides?: CallOverrides
    ): Promise<FareSpin.EntryStructOutput[]>;

    getEntryByIndex(
      roundId: BigNumberish,
      user: string,
      entryIdx: BigNumberish,
      overrides?: CallOverrides
    ): Promise<FareSpin.EntryStructOutput>;

    getEntryCount(
      roundId: BigNumberish,
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFareTokenAddress(overrides?: CallOverrides): Promise<string>;

    getIsEliminator(
      roundId: BigNumberish,
      contractModeId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isRoundPaused(overrides?: CallOverrides): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    placeBatchEntry(
      entries: FareSpin.EntryStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    rawFulfillRandomness(
      requestId: BytesLike,
      randomness: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    requestRandomNumber(overrides?: CallOverrides): Promise<string>;

    rounds(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, string, BigNumber] & {
        id: BigNumber;
        randomNum: BigNumber;
        randomEliminator: BigNumber;
        vrfRequestId: string;
        vrfNum: BigNumber;
      }
    >;

    setContractExpectedValueFloor(
      contractModeId: BigNumberish,
      _contractExpectedValueFloor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setContractMode(
      cardinality: BigNumberish,
      contractExpectedValueFloor: BigNumberish,
      mintMultiplier: BigNumberish,
      minAmount: BigNumberish,
      maxAmount: BigNumberish,
      entryLimit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setContractModeEntryLimit(
      contractModeId: BigNumberish,
      entryLimit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setContractModeIsActive(
      contractModeId: BigNumberish,
      isActive: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setContractModeMinMax(
      contractModeId: BigNumberish,
      minAmount: BigNumberish,
      maxAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setFareToken(
      _fareTokenAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setPauseContract(paused: boolean, overrides?: CallOverrides): Promise<void>;

    setRoundPaused(paused: boolean, overrides?: CallOverrides): Promise<void>;

    setTreasuryAddress(
      _treasuryAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setTreasuryMint(
      percent: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    settleBatchEntry(
      roundId: BigNumberish,
      user: string,
      overrides?: CallOverrides
    ): Promise<void>;

    testConcludeRound(
      vrfRequestId: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    testFulfillRandomness(
      vrfRequestId: BytesLike,
      randomness: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    treasuryAddress(overrides?: CallOverrides): Promise<string>;

    treasuryMint(overrides?: CallOverrides): Promise<BigNumber>;

    vrfCoordinator(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "ContractModeUpdated(uint256)"(
      contractModeId?: BigNumberish | null
    ): ContractModeUpdatedEventFilter;
    ContractModeUpdated(
      contractModeId?: BigNumberish | null
    ): ContractModeUpdatedEventFilter;

    "EntrySettled(uint256,address,bool)"(
      roundId?: BigNumberish | null,
      user?: string | null,
      hasMinted?: null
    ): EntrySettledEventFilter;
    EntrySettled(
      roundId?: BigNumberish | null,
      user?: string | null,
      hasMinted?: null
    ): EntrySettledEventFilter;

    "EntrySubmitted(uint256,uint256,address)"(
      roundId?: BigNumberish | null,
      batchId?: BigNumberish | null,
      user?: string | null
    ): EntrySubmittedEventFilter;
    EntrySubmitted(
      roundId?: BigNumberish | null,
      batchId?: BigNumberish | null,
      user?: string | null
    ): EntrySubmittedEventFilter;

    "NFTMint(uint256,address)"(
      roundId?: BigNumberish | null,
      user?: string | null
    ): NFTMintEventFilter;
    NFTMint(
      roundId?: BigNumberish | null,
      user?: string | null
    ): NFTMintEventFilter;

    "Paused(address)"(account?: null): PausedEventFilter;
    Paused(account?: null): PausedEventFilter;

    "RandomNumberRequested(bytes32)"(
      vrfRequestId?: BytesLike | null
    ): RandomNumberRequestedEventFilter;
    RandomNumberRequested(
      vrfRequestId?: BytesLike | null
    ): RandomNumberRequestedEventFilter;

    "RoundConcluded(uint256,bytes32,uint256,uint256)"(
      roundId?: BigNumberish | null,
      vrfRequestId?: BytesLike | null,
      randomNum?: null,
      randomEliminator?: null
    ): RoundConcludedEventFilter;
    RoundConcluded(
      roundId?: BigNumberish | null,
      vrfRequestId?: BytesLike | null,
      randomNum?: null,
      randomEliminator?: null
    ): RoundConcludedEventFilter;

    "RoundPausedChanged(bool)"(isPaused?: null): RoundPausedChangedEventFilter;
    RoundPausedChanged(isPaused?: null): RoundPausedChangedEventFilter;

    "Unpaused(address)"(account?: null): UnpausedEventFilter;
    Unpaused(account?: null): UnpausedEventFilter;
  };

  estimateGas: {
    CONTRACT_EXPECTED_VALUE_CEILING(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    TREASURY_MINT_CAP(overrides?: CallOverrides): Promise<BigNumber>;

    batchEntryMap(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    contractModes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAllUsersByRoundId(
      roundId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBatchEntryCount(
      roundId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCurrentContractModeId(overrides?: CallOverrides): Promise<BigNumber>;

    getCurrentRoundId(overrides?: CallOverrides): Promise<BigNumber>;

    getEliminatorsByRoundId(
      roundId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEntriesByRoundUser(
      roundId: BigNumberish,
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEntryByIndex(
      roundId: BigNumberish,
      user: string,
      entryIdx: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEntryCount(
      roundId: BigNumberish,
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFareTokenAddress(overrides?: CallOverrides): Promise<BigNumber>;

    getIsEliminator(
      roundId: BigNumberish,
      contractModeId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isRoundPaused(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    placeBatchEntry(
      entries: FareSpin.EntryStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    rawFulfillRandomness(
      requestId: BytesLike,
      randomness: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    requestRandomNumber(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    rounds(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    setContractExpectedValueFloor(
      contractModeId: BigNumberish,
      _contractExpectedValueFloor: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setContractMode(
      cardinality: BigNumberish,
      contractExpectedValueFloor: BigNumberish,
      mintMultiplier: BigNumberish,
      minAmount: BigNumberish,
      maxAmount: BigNumberish,
      entryLimit: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setContractModeEntryLimit(
      contractModeId: BigNumberish,
      entryLimit: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setContractModeIsActive(
      contractModeId: BigNumberish,
      isActive: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setContractModeMinMax(
      contractModeId: BigNumberish,
      minAmount: BigNumberish,
      maxAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setFareToken(
      _fareTokenAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setPauseContract(
      paused: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setRoundPaused(
      paused: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setTreasuryAddress(
      _treasuryAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setTreasuryMint(
      percent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    settleBatchEntry(
      roundId: BigNumberish,
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testConcludeRound(
      vrfRequestId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testFulfillRandomness(
      vrfRequestId: BytesLike,
      randomness: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    treasuryAddress(overrides?: CallOverrides): Promise<BigNumber>;

    treasuryMint(overrides?: CallOverrides): Promise<BigNumber>;

    vrfCoordinator(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    CONTRACT_EXPECTED_VALUE_CEILING(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    TREASURY_MINT_CAP(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    batchEntryMap(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    contractModes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAllUsersByRoundId(
      roundId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBatchEntryCount(
      roundId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCurrentContractModeId(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCurrentRoundId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getEliminatorsByRoundId(
      roundId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEntriesByRoundUser(
      roundId: BigNumberish,
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEntryByIndex(
      roundId: BigNumberish,
      user: string,
      entryIdx: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEntryCount(
      roundId: BigNumberish,
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFareTokenAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getIsEliminator(
      roundId: BigNumberish,
      contractModeId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isRoundPaused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    placeBatchEntry(
      entries: FareSpin.EntryStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    rawFulfillRandomness(
      requestId: BytesLike,
      randomness: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    requestRandomNumber(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    rounds(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setContractExpectedValueFloor(
      contractModeId: BigNumberish,
      _contractExpectedValueFloor: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setContractMode(
      cardinality: BigNumberish,
      contractExpectedValueFloor: BigNumberish,
      mintMultiplier: BigNumberish,
      minAmount: BigNumberish,
      maxAmount: BigNumberish,
      entryLimit: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setContractModeEntryLimit(
      contractModeId: BigNumberish,
      entryLimit: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setContractModeIsActive(
      contractModeId: BigNumberish,
      isActive: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setContractModeMinMax(
      contractModeId: BigNumberish,
      minAmount: BigNumberish,
      maxAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setFareToken(
      _fareTokenAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setPauseContract(
      paused: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setRoundPaused(
      paused: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setTreasuryAddress(
      _treasuryAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setTreasuryMint(
      percent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    settleBatchEntry(
      roundId: BigNumberish,
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testConcludeRound(
      vrfRequestId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testFulfillRandomness(
      vrfRequestId: BytesLike,
      randomness: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    treasuryAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    treasuryMint(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    vrfCoordinator(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
