/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export declare namespace FareSpinGame {
  export type EliminatorStruct = {
    gameModeId: BigNumberish;
    recordedEdgeFloor: BigNumberish;
    isEliminator: boolean;
  };

  export type EliminatorStructOutput = [BigNumber, BigNumber, boolean] & {
    gameModeId: BigNumber;
    recordedEdgeFloor: BigNumber;
    isEliminator: boolean;
  };

  export type EntryStruct = {
    amount: BigNumberish;
    gameModeId: BigNumberish;
    pickedNumber: BigNumberish;
  };

  export type EntryStructOutput = [BigNumber, BigNumber, BigNumber] & {
    amount: BigNumber;
    gameModeId: BigNumber;
    pickedNumber: BigNumber;
  };
}

export interface FareSpinGameInterface extends utils.Interface {
  contractName: "FareSpinGame";

  functions: {
    "GAME_EDGE_CEILING()": FunctionFragment;
    "batchEntryMap(uint256,address)": FunctionFragment;
    "gameModes(uint256)": FunctionFragment;
    "getAllPlayersByRoundId(uint256)": FunctionFragment;
    "getBatchEntryCount(uint256)": FunctionFragment;
    "getCurrentGameModeId()": FunctionFragment;
    "getCurrentRoundId()": FunctionFragment;
    "getEliminatorsByRoundId(uint256)": FunctionFragment;
    "getEntriesByRoundPlayer(uint256,address)": FunctionFragment;
    "getEntryByIndex(uint256,address,uint256)": FunctionFragment;
    "getEntryCount(uint256,address)": FunctionFragment;
    "getFareTokenAddress()": FunctionFragment;
    "getIsEliminator(uint256,uint256)": FunctionFragment;
    "isRoundPaused()": FunctionFragment;
    "owner()": FunctionFragment;
    "paused()": FunctionFragment;
    "placeBatchEntry((uint256,uint256,uint256)[])": FunctionFragment;
    "rawFulfillRandomness(bytes32,uint256)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "requestRandomNumber()": FunctionFragment;
    "rounds(uint256)": FunctionFragment;
    "setFareToken(address)": FunctionFragment;
    "setGameEdgeFloor(uint256,uint256)": FunctionFragment;
    "setGameMode(uint256,uint256,uint256,uint256,uint256,uint256)": FunctionFragment;
    "setGameModeEntryLimit(uint256,uint256)": FunctionFragment;
    "setGameModeIsActive(uint256,bool)": FunctionFragment;
    "setGameModeMinMax(uint256,uint256,uint256)": FunctionFragment;
    "setTreasuryAddress(address)": FunctionFragment;
    "setTreasuryMint(uint256)": FunctionFragment;
    "settleBatchEntry(uint256,address)": FunctionFragment;
    "testConcludeRound(bytes32)": FunctionFragment;
    "testFulfillRandomness(bytes32,uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "treasuryAddress()": FunctionFragment;
    "treasuryMint()": FunctionFragment;
    "vrfCoordinator()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "GAME_EDGE_CEILING"
      | "batchEntryMap"
      | "gameModes"
      | "getAllPlayersByRoundId"
      | "getBatchEntryCount"
      | "getCurrentGameModeId"
      | "getCurrentRoundId"
      | "getEliminatorsByRoundId"
      | "getEntriesByRoundPlayer"
      | "getEntryByIndex"
      | "getEntryCount"
      | "getFareTokenAddress"
      | "getIsEliminator"
      | "isRoundPaused"
      | "owner"
      | "paused"
      | "placeBatchEntry"
      | "rawFulfillRandomness"
      | "renounceOwnership"
      | "requestRandomNumber"
      | "rounds"
      | "setFareToken"
      | "setGameEdgeFloor"
      | "setGameMode"
      | "setGameModeEntryLimit"
      | "setGameModeIsActive"
      | "setGameModeMinMax"
      | "setTreasuryAddress"
      | "setTreasuryMint"
      | "settleBatchEntry"
      | "testConcludeRound"
      | "testFulfillRandomness"
      | "transferOwnership"
      | "treasuryAddress"
      | "treasuryMint"
      | "vrfCoordinator"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "GAME_EDGE_CEILING",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "batchEntryMap",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "gameModes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllPlayersByRoundId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBatchEntryCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentGameModeId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentRoundId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEliminatorsByRoundId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntriesByRoundPlayer",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntryByIndex",
    values: [BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntryCount",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getFareTokenAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getIsEliminator",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isRoundPaused",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "placeBatchEntry",
    values: [FareSpinGame.EntryStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "rawFulfillRandomness",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestRandomNumber",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rounds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFareToken",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setGameEdgeFloor",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setGameMode",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setGameModeEntryLimit",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setGameModeIsActive",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setGameModeMinMax",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasuryAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasuryMint",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "settleBatchEntry",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "testConcludeRound",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "testFulfillRandomness",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "treasuryAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "treasuryMint",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "vrfCoordinator",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "GAME_EDGE_CEILING",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchEntryMap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gameModes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllPlayersByRoundId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBatchEntryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentGameModeId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentRoundId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEliminatorsByRoundId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEntriesByRoundPlayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEntryByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEntryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFareTokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIsEliminator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRoundPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "placeBatchEntry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rawFulfillRandomness",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestRandomNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rounds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setFareToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGameEdgeFloor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGameMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGameModeEntryLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGameModeIsActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGameModeMinMax",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasuryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasuryMint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleBatchEntry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testConcludeRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testFulfillRandomness",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "treasuryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "treasuryMint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vrfCoordinator",
    data: BytesLike
  ): Result;

  events: {
    "EntrySettled(uint256,address,bool)": EventFragment;
    "EntrySubmitted(uint256,uint256,address)": EventFragment;
    "GameModeUpdated(uint256)": EventFragment;
    "NFTWon(uint256,address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "Paused(address)": EventFragment;
    "RandomNumberRequested(bytes32)": EventFragment;
    "RoundConcluded(uint256,bytes32,uint256,uint256)": EventFragment;
    "Unpaused(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "EntrySettled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EntrySubmitted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GameModeUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NFTWon"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RandomNumberRequested"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoundConcluded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
}

export interface EntrySettledEventObject {
  roundId: BigNumber;
  player: string;
  hasWon: boolean;
}
export type EntrySettledEvent = TypedEvent<
  [BigNumber, string, boolean],
  EntrySettledEventObject
>;

export type EntrySettledEventFilter = TypedEventFilter<EntrySettledEvent>;

export interface EntrySubmittedEventObject {
  roundId: BigNumber;
  batchId: BigNumber;
  player: string;
}
export type EntrySubmittedEvent = TypedEvent<
  [BigNumber, BigNumber, string],
  EntrySubmittedEventObject
>;

export type EntrySubmittedEventFilter = TypedEventFilter<EntrySubmittedEvent>;

export interface GameModeUpdatedEventObject {
  gameModeId: BigNumber;
}
export type GameModeUpdatedEvent = TypedEvent<
  [BigNumber],
  GameModeUpdatedEventObject
>;

export type GameModeUpdatedEventFilter = TypedEventFilter<GameModeUpdatedEvent>;

export interface NFTWonEventObject {
  roundId: BigNumber;
  player: string;
}
export type NFTWonEvent = TypedEvent<[BigNumber, string], NFTWonEventObject>;

export type NFTWonEventFilter = TypedEventFilter<NFTWonEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface PausedEventObject {
  account: string;
}
export type PausedEvent = TypedEvent<[string], PausedEventObject>;

export type PausedEventFilter = TypedEventFilter<PausedEvent>;

export interface RandomNumberRequestedEventObject {
  vrfRequestId: string;
}
export type RandomNumberRequestedEvent = TypedEvent<
  [string],
  RandomNumberRequestedEventObject
>;

export type RandomNumberRequestedEventFilter =
  TypedEventFilter<RandomNumberRequestedEvent>;

export interface RoundConcludedEventObject {
  roundId: BigNumber;
  vrfRequestId: string;
  randomNum: BigNumber;
  randomEliminator: BigNumber;
}
export type RoundConcludedEvent = TypedEvent<
  [BigNumber, string, BigNumber, BigNumber],
  RoundConcludedEventObject
>;

export type RoundConcludedEventFilter = TypedEventFilter<RoundConcludedEvent>;

export interface UnpausedEventObject {
  account: string;
}
export type UnpausedEvent = TypedEvent<[string], UnpausedEventObject>;

export type UnpausedEventFilter = TypedEventFilter<UnpausedEvent>;

export interface FareSpinGame extends BaseContract {
  contractName: "FareSpinGame";

  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: FareSpinGameInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    GAME_EDGE_CEILING(overrides?: CallOverrides): Promise<[BigNumber]>;

    batchEntryMap(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, boolean, BigNumber, BigNumber] & {
        batchEntryId: BigNumber;
        player: string;
        settled: boolean;
        totalEntryAmount: BigNumber;
        totalWinAmount: BigNumber;
      }
    >;

    gameModes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        boolean
      ] & {
        id: BigNumber;
        cardinality: BigNumber;
        gameEdgeFloor: BigNumber;
        mintMultiplier: BigNumber;
        minAmount: BigNumber;
        maxAmount: BigNumber;
        entryLimit: BigNumber;
        isActive: boolean;
      }
    >;

    getAllPlayersByRoundId(
      roundId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string[]] & { players: string[] }>;

    getBatchEntryCount(
      roundId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { count: BigNumber }>;

    getCurrentGameModeId(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { id: BigNumber }>;

    getCurrentRoundId(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { id: BigNumber }>;

    getEliminatorsByRoundId(
      roundId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [FareSpinGame.EliminatorStructOutput[]] & {
        eliminators: FareSpinGame.EliminatorStructOutput[];
      }
    >;

    getEntriesByRoundPlayer(
      roundId: BigNumberish,
      player: string,
      overrides?: CallOverrides
    ): Promise<[FareSpinGame.EntryStructOutput[]]>;

    getEntryByIndex(
      roundId: BigNumberish,
      player: string,
      entryIdx: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[FareSpinGame.EntryStructOutput]>;

    getEntryCount(
      roundId: BigNumberish,
      player: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { count: BigNumber }>;

    getFareTokenAddress(
      overrides?: CallOverrides
    ): Promise<[string] & { fareAddress: string }>;

    getIsEliminator(
      roundId: BigNumberish,
      gameModeId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean] & { isEliminator: boolean }>;

    isRoundPaused(overrides?: CallOverrides): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    placeBatchEntry(
      entries: FareSpinGame.EntryStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    rawFulfillRandomness(
      requestId: BytesLike,
      randomness: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    requestRandomNumber(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    rounds(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, string, BigNumber] & {
        id: BigNumber;
        randomNum: BigNumber;
        randomEliminator: BigNumber;
        vrfRequestId: string;
        vrfNum: BigNumber;
      }
    >;

    setFareToken(
      _fareTokenAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setGameEdgeFloor(
      gameModeId: BigNumberish,
      _gameEdgeFloor: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setGameMode(
      cardinality: BigNumberish,
      gameEdgeFloor: BigNumberish,
      mintMultiplier: BigNumberish,
      minAmount: BigNumberish,
      maxAmount: BigNumberish,
      entryLimit: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setGameModeEntryLimit(
      gameModeId: BigNumberish,
      entryLimit: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setGameModeIsActive(
      gameModeId: BigNumberish,
      isActive: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setGameModeMinMax(
      gameModeId: BigNumberish,
      minAmount: BigNumberish,
      maxAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setTreasuryAddress(
      _treasuryAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setTreasuryMint(
      percent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    settleBatchEntry(
      roundId: BigNumberish,
      player: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testConcludeRound(
      vrfRequestId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testFulfillRandomness(
      vrfRequestId: BytesLike,
      randomness: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    treasuryAddress(overrides?: CallOverrides): Promise<[string]>;

    treasuryMint(overrides?: CallOverrides): Promise<[BigNumber]>;

    vrfCoordinator(overrides?: CallOverrides): Promise<[string]>;
  };

  GAME_EDGE_CEILING(overrides?: CallOverrides): Promise<BigNumber>;

  batchEntryMap(
    arg0: BigNumberish,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, boolean, BigNumber, BigNumber] & {
      batchEntryId: BigNumber;
      player: string;
      settled: boolean;
      totalEntryAmount: BigNumber;
      totalWinAmount: BigNumber;
    }
  >;

  gameModes(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      boolean
    ] & {
      id: BigNumber;
      cardinality: BigNumber;
      gameEdgeFloor: BigNumber;
      mintMultiplier: BigNumber;
      minAmount: BigNumber;
      maxAmount: BigNumber;
      entryLimit: BigNumber;
      isActive: boolean;
    }
  >;

  getAllPlayersByRoundId(
    roundId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getBatchEntryCount(
    roundId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getCurrentGameModeId(overrides?: CallOverrides): Promise<BigNumber>;

  getCurrentRoundId(overrides?: CallOverrides): Promise<BigNumber>;

  getEliminatorsByRoundId(
    roundId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<FareSpinGame.EliminatorStructOutput[]>;

  getEntriesByRoundPlayer(
    roundId: BigNumberish,
    player: string,
    overrides?: CallOverrides
  ): Promise<FareSpinGame.EntryStructOutput[]>;

  getEntryByIndex(
    roundId: BigNumberish,
    player: string,
    entryIdx: BigNumberish,
    overrides?: CallOverrides
  ): Promise<FareSpinGame.EntryStructOutput>;

  getEntryCount(
    roundId: BigNumberish,
    player: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getFareTokenAddress(overrides?: CallOverrides): Promise<string>;

  getIsEliminator(
    roundId: BigNumberish,
    gameModeId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isRoundPaused(overrides?: CallOverrides): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  placeBatchEntry(
    entries: FareSpinGame.EntryStruct[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  rawFulfillRandomness(
    requestId: BytesLike,
    randomness: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  requestRandomNumber(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  rounds(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, string, BigNumber] & {
      id: BigNumber;
      randomNum: BigNumber;
      randomEliminator: BigNumber;
      vrfRequestId: string;
      vrfNum: BigNumber;
    }
  >;

  setFareToken(
    _fareTokenAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setGameEdgeFloor(
    gameModeId: BigNumberish,
    _gameEdgeFloor: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setGameMode(
    cardinality: BigNumberish,
    gameEdgeFloor: BigNumberish,
    mintMultiplier: BigNumberish,
    minAmount: BigNumberish,
    maxAmount: BigNumberish,
    entryLimit: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setGameModeEntryLimit(
    gameModeId: BigNumberish,
    entryLimit: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setGameModeIsActive(
    gameModeId: BigNumberish,
    isActive: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setGameModeMinMax(
    gameModeId: BigNumberish,
    minAmount: BigNumberish,
    maxAmount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setTreasuryAddress(
    _treasuryAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setTreasuryMint(
    percent: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  settleBatchEntry(
    roundId: BigNumberish,
    player: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testConcludeRound(
    vrfRequestId: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testFulfillRandomness(
    vrfRequestId: BytesLike,
    randomness: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  treasuryAddress(overrides?: CallOverrides): Promise<string>;

  treasuryMint(overrides?: CallOverrides): Promise<BigNumber>;

  vrfCoordinator(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    GAME_EDGE_CEILING(overrides?: CallOverrides): Promise<BigNumber>;

    batchEntryMap(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, boolean, BigNumber, BigNumber] & {
        batchEntryId: BigNumber;
        player: string;
        settled: boolean;
        totalEntryAmount: BigNumber;
        totalWinAmount: BigNumber;
      }
    >;

    gameModes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        boolean
      ] & {
        id: BigNumber;
        cardinality: BigNumber;
        gameEdgeFloor: BigNumber;
        mintMultiplier: BigNumber;
        minAmount: BigNumber;
        maxAmount: BigNumber;
        entryLimit: BigNumber;
        isActive: boolean;
      }
    >;

    getAllPlayersByRoundId(
      roundId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getBatchEntryCount(
      roundId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCurrentGameModeId(overrides?: CallOverrides): Promise<BigNumber>;

    getCurrentRoundId(overrides?: CallOverrides): Promise<BigNumber>;

    getEliminatorsByRoundId(
      roundId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<FareSpinGame.EliminatorStructOutput[]>;

    getEntriesByRoundPlayer(
      roundId: BigNumberish,
      player: string,
      overrides?: CallOverrides
    ): Promise<FareSpinGame.EntryStructOutput[]>;

    getEntryByIndex(
      roundId: BigNumberish,
      player: string,
      entryIdx: BigNumberish,
      overrides?: CallOverrides
    ): Promise<FareSpinGame.EntryStructOutput>;

    getEntryCount(
      roundId: BigNumberish,
      player: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFareTokenAddress(overrides?: CallOverrides): Promise<string>;

    getIsEliminator(
      roundId: BigNumberish,
      gameModeId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isRoundPaused(overrides?: CallOverrides): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    placeBatchEntry(
      entries: FareSpinGame.EntryStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    rawFulfillRandomness(
      requestId: BytesLike,
      randomness: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    requestRandomNumber(overrides?: CallOverrides): Promise<string>;

    rounds(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, string, BigNumber] & {
        id: BigNumber;
        randomNum: BigNumber;
        randomEliminator: BigNumber;
        vrfRequestId: string;
        vrfNum: BigNumber;
      }
    >;

    setFareToken(
      _fareTokenAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setGameEdgeFloor(
      gameModeId: BigNumberish,
      _gameEdgeFloor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setGameMode(
      cardinality: BigNumberish,
      gameEdgeFloor: BigNumberish,
      mintMultiplier: BigNumberish,
      minAmount: BigNumberish,
      maxAmount: BigNumberish,
      entryLimit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setGameModeEntryLimit(
      gameModeId: BigNumberish,
      entryLimit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setGameModeIsActive(
      gameModeId: BigNumberish,
      isActive: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setGameModeMinMax(
      gameModeId: BigNumberish,
      minAmount: BigNumberish,
      maxAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setTreasuryAddress(
      _treasuryAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setTreasuryMint(
      percent: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    settleBatchEntry(
      roundId: BigNumberish,
      player: string,
      overrides?: CallOverrides
    ): Promise<void>;

    testConcludeRound(
      vrfRequestId: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    testFulfillRandomness(
      vrfRequestId: BytesLike,
      randomness: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    treasuryAddress(overrides?: CallOverrides): Promise<string>;

    treasuryMint(overrides?: CallOverrides): Promise<BigNumber>;

    vrfCoordinator(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "EntrySettled(uint256,address,bool)"(
      roundId?: BigNumberish | null,
      player?: string | null,
      hasWon?: null
    ): EntrySettledEventFilter;
    EntrySettled(
      roundId?: BigNumberish | null,
      player?: string | null,
      hasWon?: null
    ): EntrySettledEventFilter;

    "EntrySubmitted(uint256,uint256,address)"(
      roundId?: BigNumberish | null,
      batchId?: BigNumberish | null,
      player?: string | null
    ): EntrySubmittedEventFilter;
    EntrySubmitted(
      roundId?: BigNumberish | null,
      batchId?: BigNumberish | null,
      player?: string | null
    ): EntrySubmittedEventFilter;

    "GameModeUpdated(uint256)"(
      gameModeId?: BigNumberish | null
    ): GameModeUpdatedEventFilter;
    GameModeUpdated(
      gameModeId?: BigNumberish | null
    ): GameModeUpdatedEventFilter;

    "NFTWon(uint256,address)"(
      roundId?: BigNumberish | null,
      player?: string | null
    ): NFTWonEventFilter;
    NFTWon(
      roundId?: BigNumberish | null,
      player?: string | null
    ): NFTWonEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;

    "Paused(address)"(account?: null): PausedEventFilter;
    Paused(account?: null): PausedEventFilter;

    "RandomNumberRequested(bytes32)"(
      vrfRequestId?: BytesLike | null
    ): RandomNumberRequestedEventFilter;
    RandomNumberRequested(
      vrfRequestId?: BytesLike | null
    ): RandomNumberRequestedEventFilter;

    "RoundConcluded(uint256,bytes32,uint256,uint256)"(
      roundId?: BigNumberish | null,
      vrfRequestId?: BytesLike | null,
      randomNum?: null,
      randomEliminator?: null
    ): RoundConcludedEventFilter;
    RoundConcluded(
      roundId?: BigNumberish | null,
      vrfRequestId?: BytesLike | null,
      randomNum?: null,
      randomEliminator?: null
    ): RoundConcludedEventFilter;

    "Unpaused(address)"(account?: null): UnpausedEventFilter;
    Unpaused(account?: null): UnpausedEventFilter;
  };

  estimateGas: {
    GAME_EDGE_CEILING(overrides?: CallOverrides): Promise<BigNumber>;

    batchEntryMap(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    gameModes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAllPlayersByRoundId(
      roundId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBatchEntryCount(
      roundId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCurrentGameModeId(overrides?: CallOverrides): Promise<BigNumber>;

    getCurrentRoundId(overrides?: CallOverrides): Promise<BigNumber>;

    getEliminatorsByRoundId(
      roundId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEntriesByRoundPlayer(
      roundId: BigNumberish,
      player: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEntryByIndex(
      roundId: BigNumberish,
      player: string,
      entryIdx: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEntryCount(
      roundId: BigNumberish,
      player: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFareTokenAddress(overrides?: CallOverrides): Promise<BigNumber>;

    getIsEliminator(
      roundId: BigNumberish,
      gameModeId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isRoundPaused(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    placeBatchEntry(
      entries: FareSpinGame.EntryStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    rawFulfillRandomness(
      requestId: BytesLike,
      randomness: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    requestRandomNumber(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    rounds(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    setFareToken(
      _fareTokenAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setGameEdgeFloor(
      gameModeId: BigNumberish,
      _gameEdgeFloor: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setGameMode(
      cardinality: BigNumberish,
      gameEdgeFloor: BigNumberish,
      mintMultiplier: BigNumberish,
      minAmount: BigNumberish,
      maxAmount: BigNumberish,
      entryLimit: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setGameModeEntryLimit(
      gameModeId: BigNumberish,
      entryLimit: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setGameModeIsActive(
      gameModeId: BigNumberish,
      isActive: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setGameModeMinMax(
      gameModeId: BigNumberish,
      minAmount: BigNumberish,
      maxAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setTreasuryAddress(
      _treasuryAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setTreasuryMint(
      percent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    settleBatchEntry(
      roundId: BigNumberish,
      player: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testConcludeRound(
      vrfRequestId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testFulfillRandomness(
      vrfRequestId: BytesLike,
      randomness: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    treasuryAddress(overrides?: CallOverrides): Promise<BigNumber>;

    treasuryMint(overrides?: CallOverrides): Promise<BigNumber>;

    vrfCoordinator(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    GAME_EDGE_CEILING(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    batchEntryMap(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    gameModes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAllPlayersByRoundId(
      roundId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBatchEntryCount(
      roundId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCurrentGameModeId(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCurrentRoundId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getEliminatorsByRoundId(
      roundId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEntriesByRoundPlayer(
      roundId: BigNumberish,
      player: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEntryByIndex(
      roundId: BigNumberish,
      player: string,
      entryIdx: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEntryCount(
      roundId: BigNumberish,
      player: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFareTokenAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getIsEliminator(
      roundId: BigNumberish,
      gameModeId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isRoundPaused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    placeBatchEntry(
      entries: FareSpinGame.EntryStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    rawFulfillRandomness(
      requestId: BytesLike,
      randomness: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    requestRandomNumber(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    rounds(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setFareToken(
      _fareTokenAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setGameEdgeFloor(
      gameModeId: BigNumberish,
      _gameEdgeFloor: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setGameMode(
      cardinality: BigNumberish,
      gameEdgeFloor: BigNumberish,
      mintMultiplier: BigNumberish,
      minAmount: BigNumberish,
      maxAmount: BigNumberish,
      entryLimit: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setGameModeEntryLimit(
      gameModeId: BigNumberish,
      entryLimit: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setGameModeIsActive(
      gameModeId: BigNumberish,
      isActive: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setGameModeMinMax(
      gameModeId: BigNumberish,
      minAmount: BigNumberish,
      maxAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setTreasuryAddress(
      _treasuryAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setTreasuryMint(
      percent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    settleBatchEntry(
      roundId: BigNumberish,
      player: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testConcludeRound(
      vrfRequestId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testFulfillRandomness(
      vrfRequestId: BytesLike,
      randomness: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    treasuryAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    treasuryMint(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    vrfCoordinator(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
