FROM node:lts
WORKDIR /usr/src/app
# COPY .env.prod ./.env
RUN npm install --omit=dev
EXPOSE 3100 9090
COPY . .
CMD npm run production
# CMD ls -la & node --experimental-modules --experimental-specifier-resolution=node  index.js
