/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IFareNFTLootBox,
  IFareNFTLootBoxInterface,
} from "../../../contracts/interfaces/IFareNFTLootBox";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "ownerOf",
    outputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "safeMint",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IFareNFTLootBox__factory {
  static readonly abi = _abi;
  static createInterface(): IFareNFTLootBoxInterface {
    return new utils.Interface(_abi) as IFareNFTLootBoxInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFareNFTLootBox {
    return new Contract(address, _abi, signerOrProvider) as IFareNFTLootBox;
  }
}
