/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FareItems } from "./FareItems";
export type { FareNFTLootBox } from "./FareNFTLootBox";
export type { FareNFTLootBoxController } from "./FareNFTLootBoxController";
export type { FareSpinGame } from "./FareSpinGame";
export type { FareToken } from "./FareToken";
